spring.application.name=feature-service
server.port=8083

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.streams.application-id=feature-service-streams
spring.kafka.streams.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
