spring.application.name=decision-service
server.port=8082

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

fraud.rules.path=${RULES_PATH:classpath:rules.yaml}
fraud.model.path=${MODEL_PATH:classpath:model.onnx}
